site_name: Tempest
site_url: https://cashapp.github.io/tempest/
repo_name: cashapp/tempest
repo_url: https://github.com/cashapp/tempest
site_description: "Tempest - Typesafe DynamoDB in Kotlin"
site_author: Square, Inc.
copyright: 'Copyright &copy; 2021 Square, Inc.'
remote_branch: gh-pages

theme:
  name: 'material'
  favicon: img/favicon.ico
  logo: img/cashapp.png
  palette:
    primary: 'white'
    accent: 'green'

extra_css:
  - 'css/app.css'

extra_javascript:
  - 'script/mermaid.min.js'

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - tables

plugins:
  - search
  - macros

extra:
  versions:
    tempest: '1.4.1'

nav:
  - 'Overview': index.md

  - 'Guides':
      - 'Getting Started': guide/getting_started.md
      - 'Data Modeling': guide/data_modeling.md
      - 'CRUD': guide/crud.md
      - 'Optimistic Locking': guide/optimistic_locking.md
      - 'Batch Read & Write': guide/batch_read_write.md
      - 'Query & Scan': guide/query_scan.md
      - 'Transaction': guide/transaction.md
      - 'Testing': guide/testing.md
      - 'Asynchronous Programming': guide/asynchronous_programming.md
      - 'DynamoDB Resources': guide/dynamodb_resources.md

  - 'Reference':
      - 'For AWS SDK 1.x':
          - 'tempest': 1.x/tempest/app.cash.tempest/index.md
          - 'tempest-testing': 1.x/tempest-testing/app.cash.tempest.testing/index.md
          - 'tempest-testing-jvm': 1.x/tempest-testing-jvm/app.cash.tempest.testing/index.md
          - 'tempest-testing-docker': 1.x/tempest-testing-docker/app.cash.tempest.testing/index.md
          - 'tempest-testing-junit5': 1.x/tempest-testing-junit5/app.cash.tempest.testing/index.md
          - 'tempest-testing-junit4': 1.x/tempest-testing-junit4/app.cash.tempest.testing/index.md
      - 'For AWS SDK 2.x':
          - 'tempest2': 1.x/tempest2/app.cash.tempest2/index.md
          - 'tempest2-testing': 1.x/tempest2-testing/app.cash.tempest2.testing/index.md
          - 'tempest2-testing-jvm': 1.x/tempest2-testing-jvm/app.cash.tempest2.testing/index.md
          - 'tempest2-testing-docker': 1.x/tempest2-testing-docker/app.cash.tempest2.testing/index.md
          - 'tempest2-testing-junit5': 1.x/tempest2-testing-junit5/app.cash.tempest2.testing/index.md
          - 'tempest2-testing-junit4': 1.x/tempest2-testing-junit4/app.cash.tempest2.testing/index.md

  - 'Changelog': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md
  - 'Releasing': releasing.md
