include("tempest-internal")
include("tempest")
include("tempest-bom")
include("tempest-docker")
include("tempest-dynamodb-local")
include("tempest-testing")
include("tempest-testing-internal")
include("tempest-testing-docker")
include("tempest-testing-jvm")
include("tempest-testing-junit4")
include("tempest-testing-junit5")
include("tempest2")
include("tempest2-testing")
include("tempest2-testing-internal")
include("tempest2-testing-docker")
include("tempest2-testing-jvm")
include("tempest2-testing-junit4")
include("tempest2-testing-junit5")
include(":samples:guides")
include(":samples:guides-junit4")
include(":samples:guides-junit5")
include(":samples:guides2")
include(":samples:guides2-junit4")
include(":samples:guides2-junit5")
// Don't enable this module, which depends on Java 14.
// include(":samples:javarecord")
include(":samples:musiclibrary")
include(":samples:musiclibrary2")
include(":samples:musiclibrary-testing")
include(":samples:urlshortener")
include(":samples:urlshortener2")

