/*
 * Copyright 2021 Square Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package app.cash.tempest2

import app.cash.tempest2.extensions.TempestAutoGeneratedTimestampRecordExtension
import app.cash.tempest2.extensions.WithResultExtension
import app.cash.tempest2.extensions.WithResultExtension.Companion.WithResultExtensionInstalledLast
import app.cash.tempest2.musiclibrary.testDb
import app.cash.tempest2.musiclibrary.versionedattribute.VersionedAttribute
import app.cash.tempest2.musiclibrary.versionedattribute.VersionedAttributeDb
import app.cash.tempest2.testing.logicalDb
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.junit.jupiter.api.extension.RegisterExtension
import software.amazon.awssdk.enhanced.dynamodb.Expression
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension
import software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver.defaultExtensions
import software.amazon.awssdk.services.dynamodb.model.AttributeValue
import software.amazon.awssdk.services.dynamodb.model.ConditionalCheckFailedException
import software.amazon.awssdk.services.dynamodb.model.GetItemRequest
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes

@OptIn(WithResultExtensionInstalledLast::class)
class DynamoDbViewWithResultTest {

  @RegisterExtension
  @JvmField
  val db = testDb()

  private val fakeClock = FakeClock(tickOnNow = 1.minutes)

  private val autoGeneratedTimestampRecordExtension =
    AutoGeneratedTimestampRecordExtension.builder().baseClock(fakeClock).build()

  private val tempestAutoGeneratedTimestampRecordExtension =
    TempestAutoGeneratedTimestampRecordExtension.create(fakeClock)

  private val versionedAttributeTable by lazy {
    db.logicalDb<VersionedAttributeDb>(
      defaultExtensions() + autoGeneratedTimestampRecordExtension + tempestAutoGeneratedTimestampRecordExtension + WithResultExtension.create()
    ).versionedAttributes
  }

  private val versionedAttributeTableWithoutExtension by lazy {
    db.logicalDb<VersionedAttributeDb>(
      defaultExtensions() + autoGeneratedTimestampRecordExtension
    ).versionedAttributes
  }

  @Test
  fun saveAndVerifyResult() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)

    val result = versionedAttributeTable.attributes.saveWithResult(item)
    assertThat(WithResultExtension.inMemoryItemsResult.get()).isNull()
    assertThat(result).isEqualTo(
      item.copy(
        version = 1L,
        // All tempest extension timestamps should have the same time as current time.
        created_at_instant = fakeClock.getInstant(),
        created_at_date = fakeClock.getDate(),
        updated_at_instant = fakeClock.getInstant(),
        updated_at_date = fakeClock.getDate(),
        // Dynamo extension should have run at the previous tick of the clock.
        updated_at_dynamo = fakeClock.minusTicks(1),
      )
    )
    println(result)

    fakeClock.add(1.hours)

    val updatedDescription = result.copy(
      description = "a new name for the item"
    )

    val updatedResult = versionedAttributeTable.attributes.saveWithResult(updatedDescription)
    assertThat(updatedResult).isEqualTo(
      updatedDescription.copy(
        version = 2L,
        // Only update should have changed, should be equal at the current time.
        updated_at_instant = fakeClock.getInstant(),
        updated_at_date = fakeClock.getDate(),
        // Dynamo extension should have run and updated at the previous tick of the clock.
        updated_at_dynamo = fakeClock.minusTicks(1),
      )
    )
    println(updatedResult)
  }

  @Test
  fun saveIfNotExist() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)

    val result = versionedAttributeTable.attributes.saveWithResult(item)
    assertThat(WithResultExtension.inMemoryItemsResult.get()).isNull()
    assertThat(result).isEqualTo(
      item.copy(
        version = 1L,
        // All tempest extension timestamps should have the same time as current time.
        created_at_instant = fakeClock.getInstant(),
        created_at_date = fakeClock.getDate(),
        updated_at_instant = fakeClock.getInstant(),
        updated_at_date = fakeClock.getDate(),
        // Dynamo extension should have run and updated at the previous tick of the clock.
        updated_at_dynamo = fakeClock.minusTicks(1),
      )
    )
    println(result)

    fakeClock.add(1.hours)

    val updatedDescription = result.copy(
      description = "a new name for the item"
    )

    // This fails because the item already exists.
    assertThrows<ConditionalCheckFailedException> {
      versionedAttributeTable.attributes.saveWithResult(updatedDescription, ifNotExist())
    }

    assertThat(WithResultExtension.inMemoryItemsResult.get()).isNull()
  }

  /**
   * Verify that date is converted correctly to ISO 8601 format.
   */
  @Test
  fun dateConverterFormat() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)
    versionedAttributeTable.attributes.save(item)

    val rawDbItem = db.dynamoDb.getItem(
      GetItemRequest.builder().key(
        mapOf(
          "partition_key" to AttributeValue.fromS(item.partition_key),
          "sort_key" to AttributeValue.fromS("INFO_${item.sort_key}")
        )
      ).tableName("versioned_attributes").build()
    )

    assertThat(rawDbItem.item().get("created_at_date")!!.s()).isEqualTo("1984-04-28T13:02:30.123Z")
    assertThat(rawDbItem.item().get("created_at_instant")!!.s()).isEqualTo("1984-04-28T13:02:30.123Z")
    assertThat(rawDbItem.item().get("updated_at_date")!!.s()).isEqualTo("1984-04-28T13:02:30.123Z")
    assertThat(rawDbItem.item().get("updated_at_instant")!!.s()).isEqualTo("1984-04-28T13:02:30.123Z")
  }

  @Test
  fun optimisticLocking() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)

    val result = versionedAttributeTable.attributes.saveWithResult(item)
    assertThat(WithResultExtension.inMemoryItemsResult.get()).isNull()
    assertThat(result).isEqualTo(
      item.copy(
        version = 1L,
        // All tempest extension timestamps should have the same time as current time.
        created_at_instant = fakeClock.getInstant(),
        created_at_date = fakeClock.getDate(),
        updated_at_instant = fakeClock.getInstant(),
        updated_at_date = fakeClock.getDate(),
        // Dynamo extension should have run at the previous tick of the clock.
        updated_at_dynamo = fakeClock.minusTicks(1),
      )
    )
    println(result)

    // This fails because the version is not updated.
    assertThrows<ConditionalCheckFailedException> {
      versionedAttributeTable.attributes.saveWithResult(item)
    }

    assertThat(WithResultExtension.inMemoryItemsResult.get()).isNull()
  }

  @Test
  fun failsIfExtensionNotInstalled() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)

    val ex = assertThrows<IllegalStateException> {
      versionedAttributeTableWithoutExtension.attributes.saveWithResult(item)
    }

    assertThat(ex).hasMessageContaining("Resulting Item was not updated. Did you forget to install the ApplyUpdatesExtension?")
  }

  @Test
  fun createdAtNotUpdatedWithoutExtension() {
    val item = VersionedAttribute(
      partition_key = "item_one",
      description = "one of the items",
    )

    fakeClock.add(1.hours)

    versionedAttributeTableWithoutExtension.attributes.save(item)
    val result = versionedAttributeTableWithoutExtension.attributes.load(
      VersionedAttribute.Key("item_one")
    )

    assertThat(result).isEqualTo(
      item.copy(
        version = 1L,
        created_at_instant = null,
        created_at_date = null,
        updated_at_instant = null,
        updated_at_date = null,
        // Dynamo extension should have run at the current time since the tempest extension didnt tick the clock.
        updated_at_dynamo = fakeClock.getInstant(),
      )
    )
  }

  private fun ifNotExist(): Expression {
    return Expression.builder()
      .expression("attribute_not_exists(partition_key)")
      .build()
  }
}