package app.cash.tempest.versionedattribute

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute

@DynamoDBTable(tableName = "versioned_attributes")
class VersionedAttributeItem {
  @DynamoDBHashKey
  var partition_key: String? = null

  @DynamoDBRangeKey
  var sort_key: String? = null

  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
  var updated_at: Long? = null

  @DynamoDBVersionAttribute
  var version: Long? = null
}
