package app.cash.tempest2.musiclibrary.versionedattribute

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey
import java.time.Instant

@DynamoDbBean
class VersionedAttributeItem {
  @get:DynamoDbPartitionKey
  var partition_key: String? = null

  @get:DynamoDbSortKey
  var sort_key: String? = null

  @get:DynamoDbVersionAttribute
  var version: Long? = null

  // @get:DynamoDbAutoGeneratedTimestampAttribute does not work on created_at with WRITE_IF_NOT_EXISTS for PutItem.
  var created_at: Instant? = null

  @get:DynamoDbAutoGeneratedTimestampAttribute
  var updated_at: Instant? = null

  var description: String? = null

  // For async parallel writes test to track consistent time
  // stamps and version across async coroutines.
  var one_version: Long? = null
  var one_created_at: Instant? = null
  var one_updated_at: Instant? = null

  var two_version: Long? = null
  var two_created_at: Instant? = null
  var two_updated_at: Instant? = null

  var three_version: Long? = null
  var three_created_at: Instant? = null
  var three_updated_at: Instant? = null

  var four_version: Long? = null
  var four_created_at: Instant? = null
  var four_updated_at: Instant? = null

  companion object {
    const val TABLE_NAME = "versioned_attributes"
  }
}
