package app.cash.tempest2.musiclibrary.versionedattribute

import java.time.Instant
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey

@DynamoDbBean
class VersionedAttributeItem {
  @get:DynamoDbPartitionKey
  var partition_key: String? = null

  @get:DynamoDbSortKey
  var sort_key: String? = null

  @get:DynamoDbVersionAttribute
  var version: Long? = null

  // @get:DynamoDbAutoGeneratedTimestampAttribute does not work on created_at with WRITE_IF_NOT_EXISTS for PutItem.
  var created_at: Instant? = null

  @get:DynamoDbAutoGeneratedTimestampAttribute
  var updated_at: Instant? = null

  var description: String? = null

  override fun toString(): String =
    "VersionedAttributeItem(" +
      "partition_key=$partition_key, " +
      "sort_key=$sort_key, " +
      "version=$version, " +
      "created_at=$created_at, " +
      "updated_at=$updated_at, " +
      "description=$description)"

  companion object {
    const val TABLE_NAME = "versioned_attributes"
  }
}
