// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
object Dependencies {
  val assertj = "org.assertj:assertj-core:3.18.1"
  val awsDynamodbLocal = "com.amazonaws:DynamoDBLocal:1.13.5"
  val aws2Dynamodb = "software.amazon.awssdk:dynamodb:2.15.66"
  val aws2DynamodbEnhanced = "software.amazon.awssdk:dynamodb-enhanced:2.15.66"
  val awsDynamodb = "com.amazonaws:aws-java-sdk-dynamodb:1.11.774"
  val clikt = "com.github.ajalt:clikt:2.8.0"
  val docker = "com.github.docker-java:docker-java:3.2.1"
  val findbugsJsr305 = "com.google.code.findbugs:jsr305:3.0.2"
  val guava = "com.google.guava:guava:30.0-jre"
  val junit4Api = "junit:junit:4.13"
  val junitApi = "org.junit.jupiter:junit-jupiter-api:5.7.0"
  val junitEngine = "org.junit.jupiter:junit-jupiter-engine:5.7.0"
  val junitGradlePlugin = "org.junit.platform:junit-platform-gradle-plugin:1.2.0"
  val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10"
  val kotlinReflection = "org.jetbrains.kotlin:kotlin-reflect:1.4.10"
  val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"
  val kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3"
  val kotlinxCoroutinesJdk8 = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.4.3"
  val kotlinxCoroutinesReactive = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive:1.4.3"
  val ktlintVersion = "0.40.0"
  val loggingApi = "io.github.microutils:kotlin-logging:1.7.9"
  val mavenPublishGradlePlugin = "com.vanniktech:gradle-maven-publish-plugin:0.12.0"
  val nettyBom = "io.netty:netty-bom:4.1.34.Final"
  val okio = "com.squareup.okio:okio:2.10.0"
  val shadowJarPlugin = "com.github.jengelman.gradle.plugins:shadow:6.1.0"
  val log4jCore = "org.apache.logging.log4j:log4j-core:2.16.0"
  val spotless5Plugin = "com.diffplug.spotless:spotless-plugin-gradle:5.7.0"
  val wireGradlePlugin = "com.squareup.wire:wire-gradle-plugin:3.6.0"
}
// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
