// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
object Dependencies {
  val assertj = "org.assertj:assertj-core:3.20.2"
  val aws2Dynamodb = "software.amazon.awssdk:dynamodb:2.17.134"
  val aws2DynamodbEnhanced = "software.amazon.awssdk:dynamodb-enhanced:2.17.134"
  val awsDynamodb = "com.amazonaws:aws-java-sdk-dynamodb:1.11.960"
  val awsDynamodbLocal = "com.amazonaws:DynamoDBLocal:1.13.5"
  val clikt = "com.github.ajalt:clikt:2.8.0"
  val dokkaGradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.6.10"
  val dockerCore = "com.github.docker-java:docker-java-core:3.2.13"
  val dockerTransport = "com.github.docker-java:docker-java-transport-httpclient5:3.2.13"
  val findbugsJsr305 = "com.google.code.findbugs:jsr305:3.0.2"
  val guava = "com.google.guava:guava:31.0.1-jre"
  val junit4Api = "junit:junit:4.13.2"
  val junitApi = "org.junit.jupiter:junit-jupiter-api:5.8.2"
  val junitEngine = "org.junit.jupiter:junit-jupiter-engine:5.8.2"
  val junitGradlePlugin = "org.junit.platform:junit-platform-gradle-plugin:1.2.0"
  val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
  val kotlinReflection = "org.jetbrains.kotlin:kotlin-reflect:1.6.10"
  val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:1.6.10"
  val kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3"
  val kotlinxCoroutinesJdk8 = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.5.1"
  val kotlinxCoroutinesReactive = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive:1.4.3"
  val ktlintVersion = "0.40.0"
  val log4jCore = "org.apache.logging.log4j:log4j-core:2.17.1"
  val loggingApi = "io.github.microutils:kotlin-logging:2.0.10"
  val mavenPublishGradlePlugin = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
  val nettyBom = "io.netty:netty-bom:4.1.75.Final"
  val okio = "com.squareup.okio:okio:3.0.0"
  val wireGradlePlugin = "com.squareup.wire:wire-gradle-plugin:4.2.0"
}
// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
