// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
object Dependencies {
  val assertj = "org.assertj:assertj-core:3.18.1"
  val awsDynamodbLocal = "com.amazonaws:DynamoDBLocal:1.13.5"
  val aws2Dynamodb = "software.amazon.awssdk:dynamodb:2.15.66"
  val aws2DynamodbEnhanced = "software.amazon.awssdk:dynamodb-enhanced:2.15.66"
  val awsDynamodb = "com.amazonaws:aws-java-sdk-dynamodb:1.11.774"
  val clikt = "com.github.ajalt:clikt:2.8.0"
  val docker = "com.github.docker-java:docker-java:3.2.1"
  val findbugsJsr305 = "com.google.code.findbugs:jsr305:3.0.2"
  val grpcBom = "io.grpc:grpc-bom:1.21.0"
  val guava = "com.google.guava:guava:30.0-jre"
  val guice = "com.google.inject:guice:4.2.3"
  val jCommander = "com.beust:jcommander:1.72"
  val junit4Api = "junit:junit:4.13"
  val junitApi = "org.junit.jupiter:junit-jupiter-api:5.7.0"
  val junitEngine = "org.junit.jupiter:junit-jupiter-engine:5.7.0"
  val junitGradlePlugin = "org.junit.platform:junit-platform-gradle-plugin:1.2.0"
  val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10"
  val kotlinReflection = "org.jetbrains.kotlin:kotlin-reflect:1.4.10"
  val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"
  val kotlinTest = "org.jetbrains.kotlin:kotlin-test:1.4.10"
  val kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5"
  val ktlintVersion = "0.40.0"
  val loggingApi = "io.github.microutils:kotlin-logging:1.7.9"
  val mavenPublishGradlePlugin = "com.vanniktech:gradle-maven-publish-plugin:0.12.0"
  val moshiCore = "com.squareup.moshi:moshi:1.11.0"
  val nettyBom = "io.netty:netty-bom:4.1.34.Final"
  val okHttp = "com.squareup.okhttp3:okhttp:4.10.0-RC1"
  val okHttpMockWebServer = "com.squareup.okhttp3:mockwebserver:4.10.0-RC1"
  val okio = "com.squareup.okio:okio:2.10.0"
  val retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
  val retrofitWire = "com.squareup.retrofit2:converter-wire:2.9.0"
  val shadowJarPlugin = "com.github.jengelman.gradle.plugins:shadow:6.1.0"
  val log4jCore = "org.apache.logging.log4j:log4j-core:2.14.0"
  val spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:4.5.1"
  val wireGradlePlugin = "com.squareup.wire:wire-gradle-plugin:3.6.0"
  val wireGrpcClient = "com.squareup.wire:wire-grpc-client:3.6.0"
  val wireMoshiAdapter = "com.squareup.wire:wire-moshi-adapter:3.6.0"
  val wireRuntime = "com.squareup.wire:wire-runtime:3.6.0"
}
// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
